# -*- mode: ruby -*-
# vi: set ft=ruby :

chef_server_ip = '192.168.33.10'
chef_server_port = '8889'

Vagrant.configure('2') do |config|

  config.vm.box = "centos64"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v0.1.0/centos64-x86_64-20131030.box"

  config.omnibus.chef_version = :latest
  
  config.vm.define 'master', primary: true do |master|
    master.vm.network :private_network, ip: chef_server_ip
    master.vm.hostname = 'IMmaster.vagrantup.com'
    
    master.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end

    master.vm.synced_folder "./chefconfig", "/chefconfig"

    pkg_cmd = <<SCRIPT
      yum install --assumeyes --quiet --errorlevel=0 rubygems ruby-devel
      netstat -tulpn | grep #{chef_server_port}
      if [ $? -ne 0 ]; then
        gem install chef-zero --no-ri --no-rdoc
        ( setsid chef-zero --host #{chef_server_ip} --port #{chef_server_port} ) &
        sleep 10
      fi
	    knife search 'name:chef' -c /chefconfig/knife.rb \
      --server-url http://#{chef_server_ip}:#{chef_server_port}
SCRIPT

    master.vm.provision :shell, :inline => pkg_cmd
  end
end
